name: Deploy to Azure
on:
  push:
    branches: [ master ] # Votre terminal indique "master", donc on utilise master ici
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: zip -r app.zip .
      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'abdelhamid-assamure' # Votre nom d'app sur Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip